<?php
namespace Defuse\Crypto;

interface CryptoInterface
{
    /**
     * Use this to generate a random encryption key.
     * 
     * @return string
     */
    public function createNewRandomKey();
    
    /**
     * 
     * Encrypts a message.
     * $plaintext is the message to encrypt.
     * $key is the encryption key, a value generated by CreateNewRandomKey().
     * You MUST catch exceptions thrown by this function. See docs above.
     * 
     * @param string $plaintext
     * @param string $key
     * @return string
     * @throws Ex\CannotPerformOperationException
     */
    public function encrypt($plaintext, $key);
    
    /**
     * Decrypts a ciphertext.
     * $ciphertext is the ciphertext to decrypt.
     * $key is the key that the ciphertext was encrypted with.
     * You MUST catch exceptions thrown by this function. See docs above.
     * 
     * @param string $ciphertext
     * @param string $key
     * @return type
     * @throws Ex\CannotPerformOperationException
     * @throws Ex\InvalidCiphertextException
     */
    public function decrypt($ciphertext, $key);
}
